// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Signix.Entities.Context;

#nullable disable

namespace Signix.Entities.Migrations
{
    [DbContext(typeof(SignixDbContext))]
    [Migration("20250906093017_ssoSetup")]
    partial class ssoSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Signix.Entities.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureClientId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("azure_client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("jsonb")
                        .HasColumnName("client_secret");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.Designation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_designations");

                    b.ToTable("designations", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("doc_tags");

                    b.Property<int>("DocumentStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("document_status_id");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("SigningRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("signing_room_id");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("DocumentStatusId")
                        .HasDatabaseName("ix_documents_document_status_id");

                    b.HasIndex("SigningRoomId")
                        .HasDatabaseName("ix_documents_signing_room_id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.DocumentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_document_statuses");

                    b.ToTable("document_statuses", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("code");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_modules");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_modules_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_modules_name");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsForServicePrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_service_principal");

                    b.Property<bool?>("IsForTenant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_tenant");

                    b.Property<bool>("IsForUser")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_user");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(900)
                        .HasColumnType("character varying(900)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_permissions_is_active");

                    b.HasIndex("IsForServicePrincipal")
                        .HasDatabaseName("ix_permissions_is_for_service_principal");

                    b.HasIndex("IsForUser")
                        .HasDatabaseName("ix_permissions_is_for_user");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_permissions_module_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsEditable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_editable");

                    b.Property<bool>("IsForServicePrincipal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_for_service_principal");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_roles_created_by_id");

                    b.HasIndex("CreatedDateTime")
                        .HasDatabaseName("ix_roles_created_date_time");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_roles_is_active");

                    b.HasIndex("ModifiedById")
                        .HasDatabaseName("ix_roles_modified_by_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("ModifiedById")
                        .HasDatabaseName("ix_role_permissions_modified_by_id");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permissions_role_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.SignLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer")
                        .HasColumnName("document_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.HasKey("Id")
                        .HasName("pk_sign_logs");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_sign_logs_document_id");

                    b.ToTable("sign_logs", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.Signer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DesignationId")
                        .HasMaxLength(100)
                        .HasColumnType("integer")
                        .HasColumnName("designation_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SignatureData")
                        .HasColumnType("text")
                        .HasColumnName("signature_data");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sined_at");

                    b.Property<int>("SigningRoomId")
                        .HasColumnType("integer")
                        .HasColumnName("signing_room_id");

                    b.HasKey("Id")
                        .HasName("pk_signers");

                    b.HasIndex("DesignationId")
                        .HasDatabaseName("ix_signers_designation_id");

                    b.HasIndex("SigningRoomId")
                        .HasDatabaseName("ix_signers_signing_room_id");

                    b.HasIndex("SigningRoomId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_signers_signing_room_id_email");

                    b.ToTable("signers", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.SigningRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_data");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int>("NotaryId")
                        .HasColumnType("integer")
                        .HasColumnName("notary_id");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_path");

                    b.Property<string>("SignTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("sign_tags");

                    b.Property<string>("SignedPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signed_path");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_signing_rooms");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_signing_rooms_client_id");

                    b.HasIndex("NotaryId")
                        .HasDatabaseName("ix_signing_rooms_notary_id");

                    b.ToTable("signing_rooms", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AzureAduserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("AzureADUserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MetaData")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta_data");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.UserModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer")
                        .HasColumnName("module_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_modules");

                    b.HasIndex("ModifiedById")
                        .HasDatabaseName("ix_user_modules_modified_by_id");

                    b.HasIndex("ModuleId")
                        .HasDatabaseName("ix_user_modules_module_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_modules_user_id");

                    b.HasIndex("UserId", "ModuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_modules_user_id_module_id");

                    b.ToTable("user_modules", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset>("CreatedDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date_time");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modified_by_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("UniqueId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unique_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_user_roles_created_by_id");

                    b.HasIndex("ModifiedById")
                        .HasDatabaseName("ix_user_roles_modified_by_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UniqueId")
                        .HasDatabaseName("ix_user_roles_unique_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_roles_user_id_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Signix.Entities.Entities.Document", b =>
                {
                    b.HasOne("Signix.Entities.Entities.DocumentStatus", "DocumentStatus")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documents_document_statuses_document_status_id");

                    b.HasOne("Signix.Entities.Entities.SigningRoom", "SigningRoom")
                        .WithMany("Documents")
                        .HasForeignKey("SigningRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_signing_rooms_signing_room_id");

                    b.Navigation("DocumentStatus");

                    b.Navigation("SigningRoom");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Permission", b =>
                {
                    b.HasOne("Signix.Entities.Entities.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_permissions_modules_module_id");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Role", b =>
                {
                    b.HasOne("Signix.Entities.Entities.User", "CreatedBy")
                        .WithMany("RoleCreatedBies")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roles_users_created_by_id");

                    b.HasOne("Signix.Entities.Entities.User", "ModifiedBy")
                        .WithMany("RoleModifiedBies")
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_roles_users_modified_by_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("Signix.Entities.Entities.RolePermission", b =>
                {
                    b.HasOne("Signix.Entities.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Signix.Entities.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Signix.Entities.Entities.SignLog", b =>
                {
                    b.HasOne("Signix.Entities.Entities.Document", "Document")
                        .WithMany("SignLogs")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sign_logs_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Signer", b =>
                {
                    b.HasOne("Signix.Entities.Entities.Designation", "Designation")
                        .WithMany("Signers")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_signers_designations_designation_id");

                    b.HasOne("Signix.Entities.Entities.SigningRoom", "SigningRoom")
                        .WithMany("Signers")
                        .HasForeignKey("SigningRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_signers_signing_rooms_signing_room_id");

                    b.Navigation("Designation");

                    b.Navigation("SigningRoom");
                });

            modelBuilder.Entity("Signix.Entities.Entities.SigningRoom", b =>
                {
                    b.HasOne("Signix.Entities.Entities.Client", "Client")
                        .WithMany("SigningRooms")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_signing_rooms_clients_client_id");

                    b.HasOne("Signix.Entities.Entities.User", "Notary")
                        .WithMany("SigningRooms")
                        .HasForeignKey("NotaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_signing_rooms_users_notary_id");

                    b.Navigation("Client");

                    b.Navigation("Notary");
                });

            modelBuilder.Entity("Signix.Entities.Entities.UserModule", b =>
                {
                    b.HasOne("Signix.Entities.Entities.Module", "Module")
                        .WithMany("UserModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_modules_modules_module_id");

                    b.HasOne("Signix.Entities.Entities.User", "User")
                        .WithMany("UserModules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_modules_users_user_id");

                    b.Navigation("Module");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Signix.Entities.Entities.UserRole", b =>
                {
                    b.HasOne("Signix.Entities.Entities.User", "CreatedBy")
                        .WithMany("UserRoleCreatedBies")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_roles_users_created_by_id");

                    b.HasOne("Signix.Entities.Entities.User", "ModifiedBy")
                        .WithMany("UserRoleModifiedBies")
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_roles_users_modified_by_id");

                    b.HasOne("Signix.Entities.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Signix.Entities.Entities.User", "User")
                        .WithMany("UserRoleUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Client", b =>
                {
                    b.Navigation("SigningRooms");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Designation", b =>
                {
                    b.Navigation("Signers");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Document", b =>
                {
                    b.Navigation("SignLogs");
                });

            modelBuilder.Entity("Signix.Entities.Entities.DocumentStatus", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Module", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("UserModules");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Signix.Entities.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Signix.Entities.Entities.SigningRoom", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Signers");
                });

            modelBuilder.Entity("Signix.Entities.Entities.User", b =>
                {
                    b.Navigation("RoleCreatedBies");

                    b.Navigation("RoleModifiedBies");

                    b.Navigation("SigningRooms");

                    b.Navigation("UserModules");

                    b.Navigation("UserRoleCreatedBies");

                    b.Navigation("UserRoleModifiedBies");

                    b.Navigation("UserRoleUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
