// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Signix.Entities.Entities;

public partial class Module
{
    [Key]
    public int Id { get; set; }

    [StringLength(900)]
    public string Name { get; set; } = null!;

    [StringLength(900)]
    public string Code { get; set; } = null!;

    public bool IsActive { get; set; }

    public int DisplayOrder { get; set; }

    [InverseProperty("Module")]
    public virtual ICollection<Permission> Permissions { get; set; } = new List<Permission>();

    [InverseProperty("Module")]
    public virtual ICollection<UserModule> UserModules { get; set; } = new List<UserModule>();
}