// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Signix.Entities.Entities;

[Index("Name", Name = "IDX_NotificationTemplates_Name")]
[Index("Name", Name = "Unique_NotificationTemplates_Name", IsUnique = true)]
public partial class NotificationTemplate
{
    [Key]
    public int Id { get; set; }

    [StringLength(256)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [StringLength(512)]
    public string Subject { get; set; } = null!;

    public string Body { get; set; } = null!;

    [StringLength(2000)]
    public string? To { get; set; }

    [StringLength(2000)]
    public string? Cc { get; set; }

    [StringLength(2000)]
    public string? Bcc { get; set; }

    public bool IsBodyHtml { get; set; }

    public bool? Priority { get; set; }
}