// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Signix.Entities.Entities;

public partial class Permission
{
    [Key]
    public int Id { get; set; }

    [StringLength(900)]
    public string Name { get; set; } = null!;

    [StringLength(900)]
    public string Code { get; set; } = null!;

    public int ModuleId { get; set; }

    public bool IsForUser { get; set; }

    public bool IsForServicePrincipal { get; set; }

    public bool IsActive { get; set; }

    public int DisplayOrder { get; set; }

    public bool? IsForTenant { get; set; }

    public DateTimeOffset? CreatedDateTime { get; set; }

    [ForeignKey("ModuleId")]
    [InverseProperty("Permissions")]
    public virtual Module Module { get; set; } = null!;

    [InverseProperty("Permission")]
    public virtual ICollection<RolePermission> RolePermissions { get; set; } = new List<RolePermission>();
}